version: "3.9"

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics
    restart: always
    container_name: victoria-metrics
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    volumes:
      - victoria-data:/victoria-metrics-data

  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vmagent
    ports:
      - "8429:8429" 
    command:
      - '--remoteWrite.url=http://victoria-metrics:8428/api/v1/write' # Enviar métricas para o VictoriaMetrics
      - '--promscrape.config=/etc/vmagent-config.yaml' 
    volumes:
      - ./config/vmagent/vmagent-config.yaml:/etc/vmagent-config.yaml:ro # Configuração do vmagent
    depends_on:
      - victoria-metrics

  vmalert:
    image: victoriametrics/vmalert:latest
    container_name: vmalert
    ports:
      - "8880:8880" 
    command:
      - '--datasource.url=http://victoria-metrics:8428' # Conectar ao VictoriaMetrics
      - '--rule=/etc/vmalert-rules.yaml' # Arquivo de regras de alertas
      - '--notifier.url=http://localhost:9093' # Exemplo de integração com Alertmanager (opcional)
    volumes:
      - ./config/vmalert/vmalert-rules.yaml:/etc/vmalert-rules.yaml:ro
    depends_on:
      - victoria-metrics

  target-api:
    image: python:3.9-slim
    container_name: target-api
    ports:
      - "5000:5000" # Porta da API de exemplo
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["python", "app.py"]
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: ./api
      dockerfile: Dockerfile

  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/datasources/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

  stress-test-service:
    build:
      context: ./stress-test
    container_name: stress-test-service
    ports:
      - "8081:8080"
    depends_on:
      - target-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS="--access-logfile=- --error-logfile=- --log-level=info"

volumes:
  victoria-data:
