apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://victoria-metrics:8428
    editable: false
    apiVersion: 1
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
